### ISSUE TITLE
project install fails

### ISSUE THREAD

**Issue by cevatkerim** [serverless/serverless-starter#12]
```
Serverless: Installing Serverless Project "serverless-starter"...
Serverless: Downloading project and installing dependencies...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

TypeError: Class extends value #<Serverless> is not a function or null
    at module.exports.ServerlessPlugin.browserify._this.config.requires.map._this.config.plugins.map._this.config.transforms.map._this.config.exclude.forEach._this.config.ignore.forEach._generateIncludePaths (/Users/kerimincedayi/Desktop/Modo/AWS/serverless-project/serverless-starter/node_modules/serverless-optimizer-plugin/index.js:21:37)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:286:25)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at /usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:213:24
From previous event:
    at ProjectInstall._initProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:208:27)
From previous event:
    at ProjectInstall.installProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:110:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by jordanmack** [comment]
A new version was put out yesterday that may solve this problem.

**Comment by jghaines** [comment]
Doesn't seem to. I'm getting a similar error:
ServerlessError: This plugin could not be found: serverless-optimizer-plugin

I tried the following install on Mac OS X v10.11.4:

$ sudo n latest
...
$ node --version
v5.9.1
$ sudo rm -rf /usr/local/lib/node_modules/serverless/
$ sudo npm install serverless --global
$ serverless --version
0.5.1
$ serverless project install serverless-starter
...
serverless.com, v0.5.1
...
Serverless: Installing Serverless Project "serverless-starter"...  
Serverless: Downloading project and installing dependencies...  
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: This plugin could not be found: serverless-optimizer-plugin
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless._loadPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:293:17)
    at Serverless.loadProjectPlugins (/usr/local/lib/node_modules/serverless/lib/Serverless.js:240:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:77:41
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:73:25)
    at /usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:213:24
From previous event:
    at ProjectInstall._initProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:208:27)
From previous event:
    at ProjectInstall.installProject (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInstall.js:110:12)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback](timers.js:514:5)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by austencollins** [comment]
@jghaines Could you run `npm install` from the root of the project again?  This looks like something is going wrong with npm's installation of that plugin and it may need to be done manually.

**Comment by jghaines** [comment]
As per https://github.com/serverless/serverless/issues/904

This scenario works with earlier versions of node:
$ sudo n 4.4.1

**Comment by chrissun-gs** [comment]
I also had to downgrade my version of node from v5.0.0 to v4.2
After the downgrade, running the command "sls project install serverless-starter" worked.

**Comment by jordanmack** [comment]
I was successful using Serverless v0.5.2 with the following config:

```
Usernames-Mac:Desktop username$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11
BuildVersion:   15A284
Usernames-Mac:Desktop username$ node -v
v5.9.1
Usernames-Mac:Desktop username$ npm -v
3.7.3
Usernames-Mac:Desktop username$ sls -v
0.5.2
```

**Comment by cevatkerim** [comment]
it works now with 4.2.1

**Comment by jghaines** [comment]
Confirmed. This works with the following combination

$ sw_vers -productVersion # Mac OS X version
10.11.4
$ node --version
v5.9.1
$ npm --version # was 3.7.5
3.8.5
$ serverless --version
0.5.2
$ serverless project install serverless-starter

Success!
