### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by grosser** [serverless/serverless-starter#5]
this might be me running on an old nodjs version, but a nicer warning like "Use nodejs x.y.z" would be great ...

```
serverless project install serverless-starter

/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/serverless/bin/serverless:5
let argv = require('minimist')(process.argv.slice(2));
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by grosser** [comment]
works fine on 5.7.0

**Comment by chennav** [comment]
So, what's the fix for this?

**Comment by grosser** [comment]
upadting to a newer nodejs ... worked on 5.7

**Comment by chennav** [comment]
Cool. that worked. Thanks
