### ISSUE TITLE
Error: Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by grosser** [serverless/serverless-starter#6]
```
serverless project install serverless-starter

Serverless: Installing Serverless Project "serverless-starter"...
Serverless: Downloading project and installing dependencies...
/Users/mgrosser/Code/serverless-starter/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

Error: Cannot find module '../../package.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.exports.asciiGreeting (/Users/mgrosser/Code/serverless-starter/node_modules/serverless/lib/utils/cli.js:27:13)
```

**Comment by jordanmack** [comment]
If you're still having a problem with this, please give it a try with the newly released Serverless v0.5.
